BL_Scripts = {}

BL_Scripts.Menu = 'esx_default_menu' -- ox / rage / esx_default_menu

BL_Scripts.NotifyPosition = 'top'
BL_Scripts.Position = 'top-right'

BL_Scripts.Command = 'vehiclemenu'

BL_Scripts.Banner = 'YOUR LINK' -- only for rage ui!

BL_Scripts.Debug = true 

BL_Scripts.Notify = {
    ['type'] = 'ox',-- ox / esx / bl / okok / 'functions.lua'
    ['ServerName'] = 'BL SCRIPTS',
}

BL_Scripts.Icons = {
    ['neon'] = 'car',
    ['door'] = 'door-open',
    ['window'] = 'car-side',
    ['xenon'] = 'lightbulb',
    ['global'] = 'gears',
    ['info'] = 'inbox',
    ['neon_color'] = 'paint-roller',
    ['neon_right'] = 'toggle-off',
    ['neon_left'] = 'toggle-off',
    ['neon_back'] = 'toggle-off',
    ['neon_front'] = 'toggle-off',
    ['neon_back'] =  'toggle-off',
    ['neon_all'] = 'toggle-on',
    ['door_left'] = 'door-open',
    ['door_right'] = 'door-open',
    ['door_back_left'] = 'door-open',
    ['door_back_right'] = 'door-open',
    ['door_trunk'] = 'truck',
    ['door_hook'] = 'hockey-puck',
    ['door_all'] = 'door-closed',
    ['window_left'] = 'window-restore',
    ['window_right'] = 'window-restore',
    ['window_back_left'] = 'window-restore',
    ['window_back_right'] = 'window-restore',
    ['window_all'] = 'window-maximize',
    ['engien'] = 'car-battery',
    ['auto_pilot'] = 'robot',
    ['drive_speed'] = 'gauge',
}

BL_Scripts.language = {
    ['no_vehicle'] = 'Du sitzt in keinem Auto',
    ['menu_title'] = 'BL SCRIPTS',
    ['menu_neon'] = 'Unterboden',
    ['menu_neon_description'] = 'Unterboden Einstellungen',
    ['menu_neon_color'] = 'Unterboden Farbe', 
    ['menu_neon_color_description'] = 'Andere deine Unterboden Farbe',
    ['left'] = 'Links', 
    ['right'] = 'Rechts', 
    ['back'] = 'Hinten',
    ['front'] = 'Vorne',
    ['all'] = 'Alle',
    ['light'] = 'Du hast das Licht %sgeschaltet',
    ['light_all'] = 'Du hast alle Lichter %sgeschaltet',
    ['menu_color'] = 'Welche Farbe willst du haben?',
    ['no_color'] = 'Du hast keine Farbe ausgewählt!',
    ['changed_color'] = 'Du hast deine Unterboden Farbe geändert!',
    ['menu_xenon'] = 'Scheinferfer',
    ['menu_xenon_description'] = 'Schalte deine Scheinwerfer an/aus',
    ['menu_xenon_color'] = 'Scheinwerfer Farbe',
    ['menu_xenon_color_description'] = 'Ändere dein Scheinwerfer Licht',
    ['changed_xenon'] = 'Du hast deine Scheinwerfer Farbe geändert!',
    ['menu_door'] = 'Fahrzeugtüren',
    ['menu_door_description'] = 'Fahrzeugtüren Einstellungen',
    ['door_right'] = 'Tür vorne Rechts',
    ['door_left'] = 'Tür vorne Links',
    ['door_back_right'] = 'Tür hinten Rechts',
    ['door_back_left'] = 'Tür hinten Links',
    ['door_hook'] = 'Motorhaube',
    ['door_trunk'] = 'Kofferraum',
    ['door_all'] = 'Alle',
    ['door_open'] = 'Du hast eine Tür geöffnet',
    ['door_all_open'] = 'Du hast alle Türen geöffnet',
    ['door_close'] = 'Du hast eine Tür geschlossen',
    ['door_all_close'] = 'Du hast alle Türen geschlossen',
    ['menu_window'] = 'Fensterscheiben',
    ['menu_window_description'] = 'Fensterscheiben Einstellungen',
    ['window_right'] = 'Fenster Rechts',
    ['window_left'] = 'Fenster Links',
    ['window_back_right'] = 'Fenster hinten Rechts', 
    ['window_back_left'] = 'Fenster hinten Links',
    ['window_all'] = 'Alle',
    ['window_notify'] = 'Du hast dein Fenster %sgefahren',
    ['window_all_notify'] = 'Du hast alle Fenster %sgefahren',
    ['menu_global'] = 'Allgemein',
    ['menu_global_description'] = 'Allgemeine Einstellungen',
    ['engien_onoff'] = 'Motor an/aus',
    ['engien'] = 'Du hast deinen Motor %sgeschaltet',
    ['autopilot'] = 'Autopilot',
    ['autopilot_menu_title'] = 'Wie schnell willst du Fahren?',
    ['autopilit_menu_description'] = 'Gib die km/h an',
    ['autopilot_enabled'] = 'Du hast den Autopilot aktiviert',
    ['autopilot_no_marker'] = 'Du hast keine Marker gesetzt!',
    ['autopilot_disabled'] = 'Du hast den Autopilot deaktiviert',
    ['drive'] = 'Max Speed',
    ['drive_menu_title'] = 'Maximal Geschwindigkeit',
    ['drive_menu_description'] = 'Stelle die Maximale Geschwindigkeit ein die du fahren kannst!',
    ['max_speed_notify'] = 'Du hast die Maximale Geschwindigkeit deines Autos auf %s km/h gesetzt',
    ['disable_max_speed_notify'] = 'Du hast die Maximale Geschwindigkeit deaktiviert!',
    ['menu_vehicle_info'] = 'Vehicle Menu',
    ['menu_vehicle_info_description'] = 'Allgemeine Vehicle Informationen',
    ['vehicle_fuel'] = 'FUEL: %s',
    ['vehicle_name'] = 'Name: %s',
    ['vehicle_plate'] = 'Kennzeichen: %s',
    ['vehicle_color'] = 'Farbe: %s',
    ['vehicle_turbo'] = 'Turbo:  %s',
    ['vehicle_turbo_disabled'] = 'DEAKTIVIERT',
    ['vehicle_turbo_enabled'] = 'AKTIVIERT',
}
